apiVersion: v1
kind: Service
metadata:
  name: bean-initializer-service
spec:
  selector:
    app: bean-initializer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP