apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: bean-space
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-binding
  namespace: bean-space
subjects:
  - kind: ServiceAccount
    name: default  # or your custom service account
    namespace: bean-space
roleRef:
  kind: Role
  name: leader-election-role
  apiGroup: rbac.authorization.k8s.io
